version: '3.9'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/alu_music
      - SECRET_KEY=supersecret
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: alu_music
    ports:
      - "5432:5432"