"""Fix ResumoSemanal fields

Revision ID: 1a28aa21ad8e
Revises: a3b23aee8c7d
Create Date: 2025-08-05 23:40:55.683885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a28aa21ad8e'
down_revision = 'a3b23aee8c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_semanal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_inicio', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('data_fim', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('resumo', sa.Text(), nullable=False))
        batch_op.drop_column('semana_referencia')
        batch_op.drop_column('texto_resumo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_semanal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto_resumo', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('semana_referencia', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('resumo')
        batch_op.drop_column('data_fim')
        batch_op.drop_column('data_inicio')

    # ### end Alembic commands ###
