"""Add ResumoSemanal

Revision ID: a3b23aee8c7d
Revises: 
Create Date: 2025-08-05 22:45:25.346111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b23aee8c7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumos_semanal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('semana_referencia', sa.String(length=10), nullable=False),
    sa.Column('texto_resumo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumos_semanal')
    # ### end Alembic commands ###
